#!/bin/bash
cd /var/www/html

echo "Installing Sylius backend, follow the instructions and use the following configuration settings..."
echo "Database Host: mysql"
echo "Database Port: 3306"
echo "Database Username: sylius"
echo "Database Password: sylius"
echo "Database Name: sylius_dev"

php bin/console sylius:install

echo "Installing frontend dependencies..."
yarn install
yarn run gulp
